title: Anshul Chauhan
email: anshulchauhan@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Anshul Chauhan.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
username: anshulxyz

# Build settings
plugins:
  - jekyll-feed
  - jekyll-redirect-from

markdown: kramdown
kramdown:
  input: GFM

collections:
  notes:
    output: true
    permalink: /:name

tag_page_layout: tag_page
tag_page_dir: tags

permalink: /:title
